# Makefile for the Himax touchscreen drivers.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_oos/

obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83102D)	+= hx83102d/
