obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o
obj-$(CONFIG_LGE_HANDLE_PANIC)                  += lge_handle_panic.o
obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_LGE_PM) += lge_monitor_thermal.o
obj-$(CONFIG_LGE_PM_SMPL_COUNTER) += lge_smpl_count.o
obj-$(CONFIG_LGE_USB_EMBEDDED_BATTERY) += lge_atd_mid.o
